# Site settings
title: andrewmalone.com
email: andrew@andrewmalone.com
description: ""
baseurl: ""
url: "http://andrewmalone.com"

# Build settings
markdown: kramdown
markdown_ext: "markdown,md"
kramdown:
  auto_ids: false
permalink: :categories/:year/:month/:day/:title/
exclude: [
    'node_modules',
    'package.json',
    'Gruntfile.js',
    'audio/*.wav',
    'audio/*.aiff',
    '*.py'
] 

mode: prod

collections:
  gear:
    output: true
  styleguide:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: gear
    values:
      layout: page
  -
    scope:
      path: ""
      type: styleguide
    values:
      layout: styleguide_item
      code: true