# Site settings
title: andrewmalone.com
email: andrew@andrewmalone.com
description: ""
baseurl: ""
url: "http://andrewmalone.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [
    'node_modules',
    'package.json',
    'Gruntfile.js',
    'audio/*.wav',
    'audio/*.aiff'
] 

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: post